
email: tilt@improfestival.ee
baseurl: ""
url: "https://improfestival.ee"
languages: ["ee", "en"]
timezone: "Europe/Tallinn"
exclude_from_localizations: ["assets"]
exclude:
  - Gemfile
  - .bundle
  - cart
  - .sass-cache
  - nginx.conf
  - docker-compose.yml
  - .asset-cache
  - Gemfile.lock
  - Dockerfile
  - README.md
  - .travis.yml
  - vendor
  - node_modules
  - bower.json"
environment: production

markdown: kramdown
sass:
  sass_dir: _assets/css
gems: 
 - jekyll-assets
 - jekyll-multiple-languages-plugin
 - jekyll-coffeescript

defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: team
  - scope:
      path: ""
      type: workshops
    values:
      layout: workshop
  - scope:
      path: ""
      type: performances
    values:
      layout: performance

collections:
  workshops:
    output: true
  team:
    output: true
  performances:
    output: true

assets:
  autoprefixer:
    browsers: ["last 4 versions","> 5%","IE 9"]
  cache_type: memory
  digest: true
  sources:  
    - "_assets/bower/font-awesome/fonts"
    - "_assets/bower/open-sans-fontface/fonts"
    - "_assets/bower/bootstrap-sass/assets/javascripts"
    - "_assets/bower/jquery/dist"
    - "_assets/bower"
  features:
   automatic_img_size: false

extlinks:
  attributes:
    rel: nofollow
    target: _blank
  rel_exclude:
    - 2013.improfestival.ee
    - 2014.improfestival.ee
    - 2015.improfestival.ee
    - 2016.improfestival.ee

social:
  twitter: TILT_Improfest
  facebook: https://www.facebook.com/tilt.improfestival
  ical: /schedule.ics
  instagram: https://instagram.com/tilt_improfestival
  youtube: https://www.youtube.com/channel/UC7gOmWdcrS_He1XZnj1VjBQ
  workshop_form: https://

compress_html:
  clippings: all
  ignore:
    envs:
      - development
